name: Deploy github page

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Merge master -> deploy
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: deploy
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          ref: 'deploy'

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command
      
      - name: Rename dist folder
        run: |
          cp -a dist/* docs

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          branch: 'deploy'
          github_token: ${{ secrets.GITHUB_TOKEN }}
