name: Sync deployment branch

on:
  push:
    branches:
      - master

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Merge master -> deploy
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: deploy
          github_token: ${{ secrets.GITHUB_TOKEN }}
